version: '3.1'
services:
  stat-server:
    build: stat-svc/server
    image: ewm-stat-svc-server-img
    container_name: ewm-stat-svc-server-cnt
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat_db

  stat-db:
    image: postgres:13.7-alpine
    container_name: ewm-stat-svc-db-cnt
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root