DROP TABLE IF EXISTS request;
DROP TABLE IF EXISTS event_compilation;
DROP TABLE IF EXISTS compilation;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS person;

CREATE TABLE person (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(250) NOT NULL,
	email VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE category
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE location
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat NUMERIC NOT NULL,
    lon NUMERIC NOT NULL
);

CREATE TABLE event
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    initiator          BIGINT REFERENCES person (id),
    title              VARCHAR(255) NOT NULL,
    annotation         VARCHAR(1024) NOT NULL,
    description        VARCHAR(1024),
    category           BIGINT REFERENCES category (id) ON DELETE RESTRICT,
    status             VARCHAR(256),
    paid               BOOLEAN,
    moderation         BOOLEAN DEFAULT TRUE,
    participants_limit INTEGER DEFAULT 0,
    location           BIGINT REFERENCES location (id) ON DELETE RESTRICT,
    created_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    planned_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME zone
);

CREATE TABLE compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(50) NOT NULL UNIQUE,
    pinned BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS event_compilation
(
    compilation BIGINT REFERENCES compilation (id) ON DELETE CASCADE,
    event       BIGINT REFERENCES event (id) ON DELETE CASCADE,
    CONSTRAINT compilation_event_pk PRIMARY KEY(compilation, event)
);

CREATE TABLE request (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator BIGINT REFERENCES person (id) ON DELETE CASCADE,
    event     BIGINT REFERENCES event (id) ON DELETE CASCADE,
    create_on TIMESTAMP WITHOUT TIME ZONE,
    status    VARCHAR(20)
);
